{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = inc(3)", "trace": "def test_answer():\n>       assert inc(3) == 5\nE       assert 4 == 5\nE        +  where 4 = inc(3)\n\ntest_pytest.py:8: AssertionError"}, "start": 1659517141994, "stop": 1659517141995, "uuid": "ad6fbd95-2245-4a72-b9fb-29a98d06fc98", "historyId": "df9bcdcaf6673f9b34f46d024ee19955", "testCaseId": "d936ef931c01e1a27d2f3ee0f0d86c3d", "fullName": "test_pytest#test_answer", "labels": [{"name": "suite", "value": "test_pytest"}, {"name": "host", "value": "yin"}, {"name": "thread", "value": "44844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest"}]}