{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_allure.py:10: AssertionError"}, "description": "this test fails", "start": 1659524516616, "stop": 1659524516616, "uuid": "47ce5b46-c91d-47ad-8bfb-c4537dfb3070", "historyId": "b2873979f94e50b7249573af844598f1", "testCaseId": "924c4ecc2b1e866f13aa32d5ad57625b", "fullName": "test_allure#test_failure", "labels": [{"name": "suite", "value": "test_allure"}, {"name": "host", "value": "yin"}, {"name": "thread", "value": "34176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}